const fields = [
  "patientName",
  "age",
  "gender",
  "condition",
  "chiefComplaint",
  "painScore",
  "duration",
  "objectiveFindings",
  "functionalLimitations",
  "treatmentGiven",
  "goals"
];

function getValue(id) {
  return document.getElementById(id).value.trim();
}

function createExercisePlan(condition, painScore) {
  const pain = Number(painScore);
  let exercises = [];

  if (condition === "Low Back Pain") {
    exercises = ["Pelvic tilts", "Cat-camel stretch", "Knee-to-chest stretch", "Core bracing", "Glute bridges"];
  } else if (condition === "Neck Pain") {
    exercises = ["Chin tucks", "Upper trapezius stretch", "Scapular retraction", "Neck isometrics", "Posture correction drills"];
  } else if (condition === "Knee Pain") {
    exercises = ["Quadriceps sets", "Straight leg raises", "Heel slides", "Mini squats", "Step-up training"];
  } else if (condition === "Shoulder Pain") {
    exercises = ["Pendulum exercise", "Wall climbs", "Scapular setting", "External rotation with band", "Posterior capsule stretch"];
  } else {
    exercises = ["Gentle mobility exercises", "Stretching", "Strengthening exercises", "Balance or coordination training", "Functional activity practice"];
  }

  const intensity = pain >= 7
    ? "Start with low intensity, pain-free range exercises and avoid heavy resistance."
    : pain >= 4
      ? "Use moderate intensity exercises with symptom monitoring."
      : "Progress strengthening and functional activities as tolerated.";

  return exercises.map((exercise, index) => `${index + 1}. ${exercise}`).join("\n") + "\n\nExercise Intensity Guidance: " + intensity;
}

function generateNote() {
  const patientName = getValue("patientName") || "Not provided";
  const age = getValue("age") || "Not provided";
  const gender = getValue("gender") || "Not provided";
  const condition = getValue("condition") || "Not provided";
  const chiefComplaint = getValue("chiefComplaint") || "Not provided";
  const painScore = getValue("painScore") || "Not provided";
  const duration = getValue("duration") || "Not provided";
  const objectiveFindings = getValue("objectiveFindings") || "Not provided";
  const functionalLimitations = getValue("functionalLimitations") || "Not provided";
  const treatmentGiven = getValue("treatmentGiven") || "Not provided";
  const goals = getValue("goals") || "Not provided";
  const exercisePlan = createExercisePlan(condition, painScore);
  const today = new Date().toLocaleDateString();

  const note = `PHYSIOTHERAPY DOCUMENTATION REPORT
Date: ${today}

PATIENT DETAILS
Patient Name/ID: ${patientName}
Age: ${age}
Gender: ${gender}
Primary Condition: ${condition}

SOAP NOTE

S - SUBJECTIVE
The patient reports: ${chiefComplaint}
Duration of symptoms: ${duration}
Pain score reported by patient: ${painScore}/10

O - OBJECTIVE
Clinical findings observed during assessment:
${objectiveFindings}

Functional limitations:
${functionalLimitations}

Treatment/intervention provided today:
${treatmentGiven}

A - ASSESSMENT
The patient presents with symptoms consistent with ${condition}. Current findings suggest pain, reduced functional ability, and movement limitations affecting daily activities. The patient may benefit from a structured physiotherapy program focused on pain reduction, mobility improvement, strengthening, posture correction, and functional retraining.

P - PLAN
Treatment goals:
${goals}

Recommended treatment plan:
1. Continue physiotherapy sessions based on symptom severity and functional needs.
2. Educate patient about posture, activity modification, and safe movement patterns.
3. Begin or continue therapeutic exercises within pain-free limits.
4. Reassess pain score, movement quality, and function during follow-up sessions.
5. Progress exercises gradually according to patient tolerance.

SUGGESTED HOME EXERCISE PLAN
${exercisePlan}

DISCLAIMER
This report is generated by an academic prototype and should be reviewed by a qualified physiotherapist before clinical use.`;

  document.getElementById("output").textContent = note;
  return note;
}

function saveSession() {
  const note = generateNote();
  const patientName = getValue("patientName") || "Unnamed patient";
  const saved = JSON.parse(localStorage.getItem("physioSessions") || "[]");

  saved.unshift({
    patientName,
    date: new Date().toLocaleString(),
    note
  });

  localStorage.setItem("physioSessions", JSON.stringify(saved));
  showSavedSessions();
  alert("Session saved successfully.");
}

function showSavedSessions() {
  const saved = JSON.parse(localStorage.getItem("physioSessions") || "[]");
  const container = document.getElementById("savedSessions");

  if (saved.length === 0) {
    container.innerHTML = "<p>No saved sessions yet.</p>";
    return;
  }

  container.innerHTML = saved.map((session, index) => `
    <div class="saved-item">
      <strong>${session.patientName}</strong><br />
      ${session.date}<br />
      <button class="secondary" onclick="loadSession(${index})">View</button>
    </div>
  `).join("");
}

function loadSession(index) {
  const saved = JSON.parse(localStorage.getItem("physioSessions") || "[]");
  document.getElementById("output").textContent = saved[index].note;
}

function downloadReport() {
  const note = document.getElementById("output").textContent;

  if (!note || note.includes("Fill the assessment form")) {
    alert("Please generate a SOAP note first.");
    return;
  }

  const file = new Blob([note], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(file);
  link.download = "physiotherapy-report.txt";
  link.click();
  URL.revokeObjectURL(link.href);
}

function clearForm() {
  fields.forEach(id => {
    document.getElementById(id).value = "";
  });

  document.getElementById("output").textContent = 'Fill the assessment form and click "Generate SOAP Note".';
}

document.getElementById("generateButton").addEventListener("click", generateNote);
document.getElementById("saveButton").addEventListener("click", saveSession);
document.getElementById("downloadButton").addEventListener("click", downloadReport);
document.getElementById("clearButton").addEventListener("click", clearForm);

showSavedSessions();
